import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, BarChart3, Check, ChevronRight, Dumbbell, Flame, History, Plus, Settings, Sparkles, Timer, Trash2, Trophy } from 'lucide-react';
import './styles.css';

const STORAGE_KEY='repcounter-v1';
const baseWorkouts={Push:['Bench Press','Incline Dumbbell Press','Shoulder Press','Dips','Cable Fly'],Pull:['Lat Pulldown','Barbell Row','Seated Cable Row','Face Pull','Bicep Curl'],Legs:['Back Squat','Romanian Deadlift','Leg Press','Leg Curl','Calf Raise']};
const seed={workouts:baseWorkouts,logs:[{id:'a',workout:'Push',exercise:'Bench Press',weight:80,reps:8,at:'2026-06-20T10:24:31'},{id:'b',workout:'Push',exercise:'Bench Press',weight:85,reps:6,at:'2026-06-27T10:18:15'},{id:'c',workout:'Push',exercise:'Bench Press',weight:90,reps:5,at:'2026-07-04T09:54:12'}]};
const load=()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||seed}catch{return seed}};
const e1rm=(w,r)=>Math.round((w*(1+r/30))*10)/10;
const niceDate=s=>new Intl.DateTimeFormat('nl-NL',{dateStyle:'medium',timeStyle:'short'}).format(new Date(s));

function App(){
 const [data,setData]=useState(load); const [view,setView]=useState('workouts'); const [selected,setSelected]=useState('Push'); const [active,setActive]=useState(null); const [draft,setDraft]=useState({weight:80,reps:8});
 useEffect(()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(data)),[data]);
 const progress=useMemo(()=>data.logs.filter(x=>x.exercise==='Bench Press').map(x=>({...x,score:e1rm(x.weight,x.reps)})),[data.logs]);
 const best=progress.reduce((m,x)=>Math.max(m,x.score),0); const advice=best?Math.ceil((best+1.25)/2.5)*2.5:60;
 const addExercise=()=>{const name=prompt('Naam van de oefening'); if(!name?.trim())return; setData(d=>({...d,workouts:{...d.workouts,[selected]:[...d.workouts[selected],name.trim()]}}))};
 const removeExercise=(name)=>setData(d=>({...d,workouts:{...d.workouts,[selected]:d.workouts[selected].filter(x=>x!==name)}}));
 const logSet=()=>{if(!active)return; const item={id:crypto.randomUUID(),workout:selected,exercise:active,weight:Number(draft.weight),reps:Number(draft.reps),at:new Date().toISOString()};setData(d=>({...d,logs:[...d.logs,item]}));};
 return <div className="app-shell"><Sidebar view={view} setView={setView}/><main>
  {view==='workouts'&&<><Header title="Workouts" subtitle="Kies een schema en begin direct"/><section className="hero-grid"><div className="glass intro"><span className="eyebrow"><Flame size={16}/> Vandaag</span><h2>Klaar om sterker te worden?</h2><p>Alles wordt automatisch per datum en tijdstip opgeslagen.</p></div><Stat label="Sets gelogd" value={data.logs.length} icon={<Activity/>}/><Stat label="Beste e1RM" value={`${best||0} kg`} icon={<Trophy/>}/></section><div className="workout-grid">{Object.keys(data.workouts).map((w,i)=><button key={w} className={`workout-card c${i}`} onClick={()=>{setSelected(w);setView('session')}}><div><span>{w}</span><small>{data.workouts[w].length} oefeningen</small></div><ChevronRight/></button>)}</div></>}
  {view==='session'&&<><Header title={`${selected} workout`} subtitle="Pas oefeningen aan of log je sets"/><div className="session-layout"><section className="glass exercise-list"><div className="section-title"><div><h3>Oefeningen</h3><p>Tik op een oefening om een set te loggen</p></div><button className="soft" onClick={addExercise}><Plus size={17}/>Toevoegen</button></div>{data.workouts[selected].map(name=><div className={`exercise-row ${active===name?'active':''}`} key={name} onClick={()=>setActive(name)}><div className="exercise-icon"><Dumbbell/></div><div className="grow"><b>{name}</b><small>{data.logs.filter(x=>x.exercise===name).length} sets gelogd</small></div><button className="icon-btn" onClick={e=>{e.stopPropagation();removeExercise(name)}}><Trash2 size={17}/></button></div>)}</section><section className="glass logger"><span className="eyebrow"><Timer size={16}/> Set logger</span><h3>{active||'Selecteer een oefening'}</h3><label>Gewicht (kg)<input type="number" value={draft.weight} onChange={e=>setDraft({...draft,weight:e.target.value})}/></label><label>Herhalingen<input type="number" value={draft.reps} onChange={e=>setDraft({...draft,reps:e.target.value})}/></label><button className="primary" disabled={!active} onClick={logSet}><Check size={18}/>Set opslaan</button><p className="hint">Exacte datum en timestamp worden automatisch toegevoegd.</p></section></div></>}
  {view==='history'&&<><Header title="Geschiedenis" subtitle="Alle trainingen chronologisch opgeslagen"/><section className="glass history-list">{[...data.logs].reverse().map(x=><article key={x.id}><div className="timeline-dot"/><div><b>{x.exercise}</b><p>{x.workout} · {x.weight} kg × {x.reps} reps</p></div><time>{niceDate(x.at)}</time></article>)}</section></>}
  {view==='progress'&&<><Header title="Progressie" subtitle="Bekijk je krachtontwikkeling en volgende PR"/><div className="progress-layout"><section className="glass chart-card"><div className="section-title"><div><h3>Bench Press e1RM</h3><p>Geschatte 1RM op basis van je gelogde sets</p></div><BarChart3/></div><ProgressChart points={progress}/></section><section className="glass pr-card"><span className="eyebrow"><Sparkles size={16}/> Slim PR-advies</span><h3>Volgend doel</h3><div className="pr-number">{advice} kg</div><p>Probeer dit gewicht voor 3 tot 5 nette reps. Verhoog alleen als je techniek stabiel blijft.</p><div className="advice-chip">+2,5 kg stap</div></section></div></>}
 </main><MobileNav view={view} setView={setView}/></div>
}
function Header({title,subtitle}){return <header><div><h1>{title}</h1><p>{subtitle}</p></div><button className="avatar">H</button></header>}
function Stat({label,value,icon}){return <div className="glass stat"><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></div>}
function Sidebar({view,setView}){return <aside><div className="brand"><div className="logo"><Dumbbell/></div><b>Rep<span>Counter</span></b></div><nav>{[['workouts',Dumbbell,'Workouts'],['history',History,'Historie'],['progress',BarChart3,'Progressie']].map(([id,I,t])=><button className={view===id||view==='session'&&id==='workouts'?'selected':''} onClick={()=>setView(id)} key={id}><I size={19}/>{t}</button>)}</nav><div className="aside-bottom"><Settings size={18}/>Versie 0.1.0</div></aside>}
function MobileNav({view,setView}){return <nav className="mobile-nav">{[['workouts',Dumbbell,'Workouts'],['history',History,'Historie'],['progress',BarChart3,'Progressie']].map(([id,I,t])=><button className={view===id||view==='session'&&id==='workouts'?'selected':''} onClick={()=>setView(id)} key={id}><I size={19}/><small>{t}</small></button>)}</nav>}
function ProgressChart({points}){if(!points.length)return <div className="empty">Log eerst een set om progressie te zien.</div>;const max=Math.max(...points.map(p=>p.score))+5,min=Math.min(...points.map(p=>p.score))-5;const coords=points.map((p,i)=>`${20+i*(260/Math.max(points.length-1,1))},${145-((p.score-min)/(max-min||1))*110}`).join(' ');return <svg viewBox="0 0 300 170" className="chart"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#8b5cf6" stopOpacity=".42"/><stop offset="1" stopColor="#8b5cf6" stopOpacity="0"/></linearGradient></defs><polyline points={`20,145 ${coords} 280,145`} fill="url(#fill)" stroke="none"/><polyline points={coords} fill="none" stroke="#9b7bff" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/>{points.map((p,i)=><circle key={p.id} cx={20+i*(260/Math.max(points.length-1,1))} cy={145-((p.score-min)/(max-min||1))*110} r="5" fill="#fff" stroke="#8b5cf6" strokeWidth="3"/>)}</svg>}
createRoot(document.getElementById('root')).render(<App/>);
